### ISSUE TITLE
Set up DB

### ISSUE THREAD

**Issue by bkadu** [bkadu/uplifting-app#1]
DB Architecture 

Quotes
  - quoteID (auto incremented int)
  - quotes (string)
  - submittedBy (string)
  - verified (boolean)
  - insertTimestamp (Date/time)
  - likes
  - dislikes
Users
  - userID
  - name 
  - slackID
  - password
Comments
  - commentID
  - userID
  - quoteID
  - verified
  - comment
  - insertTS

**Comment by brentbundang** [comment]
Can we add "Author" and possibly "Category("?") to the Quotes table @bkadu 

Category column could help the machine learning stuff we can do further down the line I think

**Comment by brentbundang** [comment]
Author being the Author of the quote
